name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Extract repository name
        id: repo-name
        run: echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22022
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd dev
            cd ${{ env.REPO_NAME }}
            git pull https://${{ secrets.GIT_TOKEN }}@github.com/mind-developer/${{ env.REPO_NAME }}.git ${{ github.ref_name }}
            docker stop ${{ env.REPO_NAME }}
            docker remove ${{ env.REPO_NAME }}
            docker rmi ${{ env.REPO_NAME }}:${{ secrets.APP_PORT }}
            docker build --network host -t ${{ env.REPO_NAME }}:${{ secrets.APP_PORT }} .
            docker run --network host --restart unless-stopped -d -p ${{ secrets.APP_PORT }}:${{ secrets.APP_PORT }} --name ${{ env.REPO_NAME }} -v ${{ env.REPO_NAME }}:/uploads ${{ env.REPO_NAME }}:${{ secrets.APP_PORT }}
